/**
 * Repository traversal.
 *
 * Correctness bar: the file set must match what `git ls-files` would report,
 * because that is what a developer means by "my code". Getting this wrong in
 * either direction is expensive — missing files make the graph lie by omission,
 * and extra files (node_modules, build output) bloat the index and poison search
 * relevance.
 *
 * The `.gitignore` spec is genuinely subtle: patterns are relative to the file
 * that declares them, negations can re-include, a trailing slash means
 * directory-only, and a leading slash anchors. We delegate all of it to the
 * `ignore` package rather than hand-rolling regexes.
 */

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { createHash } from 'node:crypto';
import ignore from 'ignore';
import { toPosix, relFromRoot } from './paths.js';

/** Filenames that contribute ignore rules, in the order git applies them. */
const IGNORE_FILES = ['.gitignore', '.cgraphignore'];

/**
 * A stack of ignore matchers, one frame per directory that declared rules.
 * Testing a path walks the stack, evaluating each frame against the path
 * relative to the directory that declared it — which is what makes nested
 * `.gitignore` files behave like git.
 */
class IgnoreStack {
  constructor(frames = []) {
    this.frames = frames;
  }

  /** Return a new stack with rules from `dirRel` pushed on. */
  push(dirRel, patterns) {
    if (!patterns.length) return this;
    const matcher = ignore().add(patterns);
    return new IgnoreStack([...this.frames, { base: dirRel, matcher }]);
  }

  /**
   * Test a repo-relative path. `isDir` matters because directory-only patterns
   * (`build/`) must not match a file of the same name.
   */
  ignores(rel, isDir) {
    let ignored = false;
    for (const frame of this.frames) {
      const sub = frame.base ? rel.slice(frame.base.length + 1) : rel;
      // A frame only governs paths beneath its own directory.
      if (frame.base && !rel.startsWith(frame.base + '/')) continue;
      if (!sub) continue;

      // `ignore` distinguishes directories by trailing slash.
      const probe = isDir ? sub + '/' : sub;
      const result = frame.matcher.test(probe);
      // Later frames (deeper directories) override earlier ones, and an explicit
      // un-ignore in a deeper file must be able to rescue a parent's ignore.
      if (result.ignored) ignored = true;
      else if (result.unignored) ignored = false;
    }
    return ignored;
  }
}

function readPatterns(file) {
  try {
    return fs
      .readFileSync(file, 'utf8')
      .split(/\r?\n/)
      .filter((l) => l.trim() && !l.startsWith('#'));
  } catch {
    return [];
  }
}

/**
 * Ignore rules that apply repo-wide but don't live in a tracked `.gitignore`:
 * `.git/info/exclude` and the user's global excludes file.
 */
function globalPatterns(root) {
  const patterns = [];
  patterns.push(...readPatterns(path.join(root, '.git', 'info', 'exclude')));

  let excludesFile = process.env.GIT_GLOBAL_EXCLUDES;
  if (!excludesFile) {
    // Parse ~/.gitconfig directly rather than shelling out to git: the tool must
    // work in repos where git isn't installed or isn't on PATH.
    const gitconfig = path.join(os.homedir(), '.gitconfig');
    const text = fs.existsSync(gitconfig) ? fs.readFileSync(gitconfig, 'utf8') : '';
    const m = text.match(/^\s*excludesfile\s*=\s*(.+)$/im);
    if (m) excludesFile = m[1].trim();
  }
  if (excludesFile) {
    const resolved = excludesFile.startsWith('~')
      ? path.join(os.homedir(), excludesFile.slice(1))
      : excludesFile;
    patterns.push(...readPatterns(resolved));
  }
  return patterns;
}

/** A file is binary if its first block contains a NUL byte — same test git uses. */
function looksBinary(buf) {
  const n = Math.min(buf.length, 8000);
  for (let i = 0; i < n; i++) if (buf[i] === 0) return true;
  return false;
}

/**
 * Detect machine-written files that are technically source but worthless to
 * index: minified bundles, generated clients, compiled protobufs. They produce
 * thousands of nodes nobody will ever query and drown out real symbols.
 */
function generatedReason(rel, content, config) {
  const head = content.slice(0, 2000);
  if (/@generated|Code generated by|DO NOT EDIT|auto-generated by/i.test(head)) {
    return 'generated';
  }

  const newlines = (content.match(/\n/g) || []).length + 1;
  const meanLine = content.length / newlines;
  if (meanLine > config.maxMeanLineLength) return 'minified';

  return null;
}

function hashContent(buf) {
  // Not cryptographic — this only answers "did the bytes change". Truncating to
  // 16 bytes halves the storage across hundreds of thousands of rows.
  return createHash('sha256').update(buf).digest('hex').slice(0, 32);
}

/**
 * Walk the repository, yielding one record per candidate file.
 *
 * Yields `{ rel, abs, size, mtime, hash, content, skipReason }`. A record with a
 * `skipReason` is still yielded — the file is recorded as a stub so `map` can
 * show it exists, but it is never parsed. Silently omitting files would make the
 * graph lie about what the repo contains.
 *
 * @param {object} [opts]
 * @param {boolean} [opts.readContent]
 * @param {(rel: string, stat: {size:number, mtime:number}) => boolean} [opts.isUnchanged]
 *   Fast path. When it returns true the file is yielded as
 *   `{ rel, abs, size, mtime, unchanged: true }` and its contents are never
 *   read. Turning "has anything changed?" from a read of every byte into a
 *   stat of every file is what makes automatic refresh affordable — measured on
 *   llama.cpp, 521ms becomes 166ms.
 */
export function* walk(root, config, { readContent = true, isUnchanged = null } = {}) {
  const rootStack = new IgnoreStack().push('', [
    ...globalPatterns(root),
    ...(config.ignore ?? []),
  ]);

  yield* walkDir(root, '', rootStack, config, readContent, isUnchanged);
}

function* walkDir(root, dirRel, stack, config, readContent, isUnchanged) {
  const abs = dirRel ? path.join(root, dirRel) : root;

  let entries;
  try {
    entries = fs.readdirSync(abs, { withFileTypes: true });
  } catch {
    return; // Unreadable directory (permissions, race with a delete). Skip it.
  }

  // Ignore files in this directory apply to everything below it, so they must be
  // loaded before any child is tested.
  let localStack = stack;
  for (const name of IGNORE_FILES) {
    if (entries.some((e) => e.name === name && e.isFile())) {
      localStack = localStack.push(dirRel, readPatterns(path.join(abs, name)));
    }
  }

  // Directories first keeps output stable and makes the traversal order
  // predictable in tests.
  entries.sort((a, b) => {
    if (a.isDirectory() !== b.isDirectory()) return a.isDirectory() ? -1 : 1;
    return a.name < b.name ? -1 : a.name > b.name ? 1 : 0;
  });

  for (const entry of entries) {
    const rel = dirRel ? `${dirRel}/${entry.name}` : entry.name;

    // Symlinks are not followed: they cause infinite loops and duplicate content
    // under a different path, which would double-count every symbol.
    if (entry.isSymbolicLink()) continue;

    if (entry.isDirectory()) {
      if (entry.name === '.git') continue;
      // Testing the directory before descending is the main performance win:
      // it prunes node_modules without stat-ing a single file inside it.
      if (localStack.ignores(rel, true)) continue;
      yield* walkDir(root, rel, localStack, config, readContent, isUnchanged);
      continue;
    }

    if (!entry.isFile()) continue;
    if (localStack.ignores(rel, false)) continue;

    const absFile = path.join(abs, entry.name);
    let stat;
    try {
      stat = fs.statSync(absFile);
    } catch {
      continue;
    }

    const base = { rel, abs: absFile, size: stat.size, mtime: Math.floor(stat.mtimeMs) };

    // Cheapest possible exit: the caller already knows this file and its stat is
    // identical. Nothing is read, hashed, or parsed.
    if (isUnchanged && isUnchanged(rel, base)) {
      yield { ...base, unchanged: true };
      continue;
    }

    if (stat.size > config.maxFileBytes) {
      yield { ...base, hash: `size:${stat.size}:${base.mtime}`, skipReason: 'too-large' };
      continue;
    }

    if (!readContent) {
      yield { ...base, hash: `stat:${stat.size}:${base.mtime}` };
      continue;
    }

    let buf;
    try {
      buf = fs.readFileSync(absFile);
    } catch {
      continue;
    }

    const hash = hashContent(buf);
    if (looksBinary(buf)) {
      yield { ...base, hash, skipReason: 'binary' };
      continue;
    }

    const content = buf.toString('utf8');
    const skipReason = generatedReason(rel, content, config);
    yield { ...base, hash, content, skipReason };
  }
}

/**
 * Collect the walk into an array. Convenient for the CLI and tests; the
 * generator form is what indexing uses so memory stays flat on large repos.
 */
export function collect(root, config, opts) {
  return [...walk(root, config, opts)];
}

export { toPosix, relFromRoot };
